# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=120, null=True)),
                ('Companylogo', models.FileField(upload_to=b'')),
                ('Address', models.CharField(max_length=120, null=True)),
                ('Location', models.CharField(max_length=120, null=True)),
                ('PhoneNumber', models.IntegerField()),
                ('Website', models.URLField()),
                ('Facebook', models.URLField()),
                ('Twitter', models.URLField()),
                ('Instagram', models.URLField()),
                ('BusinessDescription', tinymce.models.HTMLField()),
                ('Business_Category', models.CharField(max_length=120, null=True)),
                ('Updated', models.DateTimeField(auto_now_add=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
