# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.ImageField(default=True, upload_to=b'')),
                ('CompanyName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Businesses.Business')),
            ],
        ),
    ]
